//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppRecrutare
{
    using System;
    using System.Collections.Generic;
    
    public partial class anunturi
    {
        public int a_id { get; set; }
        public Nullable<int> a_jid { get; set; }
        public string a_firma { get; set; }
        public string a_post { get; set; }
        public string a_locatie { get; set; }
        public string a_salariu { get; set; }
        public string a_platf { get; set; }
        public Nullable<System.DateTime> a_date { get; set; }
        public string a_link { get; set; }
    
        public virtual job job { get; set; }
    }
}
